version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=808985146341.dkr.ecr.eu-north-1.amazonaws.com/test-register1
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo "Building images..."
      - docker-compose -f docker-compose.yaml build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Pushing images to ECR..."
      - docker push 808985146341.dkr.ecr.eu-north-1.amazonaws.com/test-register1:charging-service-${IMAGE_TAG}
      - docker push 808985146341.dkr.ecr.eu-north-1.amazonaws.com/test-register1:auth-service-${IMAGE_TAG}
      - echo "Pushed images with tag: ${IMAGE_TAG}"
      - echo "Push completed successfully!"

artifacts:
  files:
    - 'docker-compose.yaml'
#    - 'env_vars'


